---
- name: Copy zabbix repo
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
    dest: /tmp/
    timeout: 30
    validate_certs: false
- name: Install zabbix repo
  ansible.builtin.package:
    name: /tmp/zabbix-release-6.0-4.el8.noarch.rpm
    state: present
    disable_gpg_check: true
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
- name: clean dnf cash
  command: dnf clean all


- name: Install Zabbix web front
  ansible.builtin.dnf:
    name: 
      - zabbix-web-pgsql
      - zabbix-nginx-conf
      - zabbix-selinux-policy
      - policycoreutils-python-utils
    state: present


- name: Adjust selinux
  shell: |
    setsebool -P httpd_can_connect_zabbix on
    setsebool -P httpd_can_network_connect_db on
    semanage permissive -a zabbix_t
  args: 
    executable: /bin/bash


- name: Copy Zabbix nginx main configuration
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf


- name: Copy Zabbix nginx conf.d for zabbix
  ansible.builtin.template:
    src: templates/zabbix.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf


- name: Copy Zabbix web php conf
  ansible.builtin.template:
    src: templates/zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php


- name: Enable and restart php
  ansible.builtin.service:
    name: php-fpm
    enabled: true
    state: restarted

- name: Enable and restart Nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: restarted