---
- name: Copy zabbix repo
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
    dest: /tmp/
    timeout: 30
    validate_certs: false
- name: Install zabbix repo
  ansible.builtin.package:
    name: /tmp/zabbix-release-6.0-4.el8.noarch.rpm
    state: present
    disable_gpg_check: true
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
- name: clean dnf cash
  command: dnf clean all


- name: Install Zabbix agent
  ansible.builtin.dnf:
    name: 
      - zabbix-agent
      - zabbix-selinux-policy
      - policycoreutils-python-utils
    state: present


- name: Adjust selinux
  shell: |
    semanage permissive -a zabbix_agent_t
  args: 
    executable: /bin/bash


- name: Copy Zabbix agent configuration
  ansible.builtin.template:
    src: templates/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf


- name: Enable and restart Zabbix agent
  ansible.builtin.service:
    name: zabbix-agent
    enabled: true
    state: restarted

